More configuration for prompt-able options
vivait/symfony-console-promptable-options pull request #2
Opened 2017-02-27 21:34 UTC by leightonthomas

Adds default values, input value transformers, repeated asking of input and optional required-ness for options by using the Symfony OptionsResolver component

I was planning to use it a little more than I did which is why I used it in the first place but I think it works nicely for the initial configuration

In theory it shouldn't break any existing commands that use `addOption()` **and** `addPrompt()` because it checks if an option's already defined with that name

2017-02-28 09:07 UTC, Brunty requested changes

2017-02-28 09:07 UTC, Brunty commented on src/Transformer/FloatTransformer.php
> +        } else {
No need for the else here.

2017-02-28 09:07 UTC, Brunty commented on src/Transformer/IntegerTransformer.php
> +        } else {
No need for the else here.

2017-02-28 09:07 UTC, Brunty commented on README.md
> +| required | Whether or not the option is required. If it's set to true, then a value MUST be entered and they will be prompted until one is provided. If set to false, a default value will be used if
Just wondering why required is needed as an option, the point of the promptable stuff was to make options required anyway, trying to think of the use case for making something promptable but not required.

Would it be like a friendly "hey, you can supply this if you want?"

2017-02-28 18:35 UTC, leightonthomas commented on README.md
> +| required | Whether or not the option is required. If it's set to true, then a value MUST be entered and they will be prompted until one is provided. If set to false, a default value will be used if
Yeah, I added it as more of "some sort of input is required for the code to function", for example if somebody forgot to provide an `age` but a value is necessary for the command to complete, you would set it to to be required, but you could also set it to false (which is the default) if it's an entirely optional thing code-wise.

2017-02-28 18:43 UTC, leightonthomas commented on src/Transformer/FloatTransformer.php
> +        } else {
Fixed in next commit

2017-02-28 18:44 UTC, leightonthomas commented on src/Transformer/IntegerTransformer.php
> +        } else {
Fixed in next commit

2017-03-01 09:03 UTC, Brunty approved these changes

2017-03-01 09:06 UTC, merged